name: 'Create Branch'
description: 'Creates a branch'
author: 'Peter Grainger (peter@grainger)'
inputs:
  branch:
    description: 'The branch to create'
    default: 'release-candidate'
runs:
  using: 'node12'
  main: 'lib/main.js'
